### ISSUE TITLE
Interactive Placenames / Camps

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#45]
Clicking on placename (or maybe a Camp Icon, or maybe a Camp Icon added to placenames?) could show more details about that location. Challenge is how to squeeze the info (sat-map etc) into a smaller-popup, but maybe could do a full-page popup for these? 

Lance has some info/text for the non-camp places (Malsit, Owen, Tsquadra etc)

**Comment by Pachena** [comment]
Suggest adding a camp icon to the camps and an "i" info icon to the other locations. Camp icons could go to the camp page (description and map) while the info icons can provide info about that location. This also gives us an opportunity to include more First Nations information as many of the info locations are First Nation territory / locations.

Info icons lead to popup

Camp icons could do popup or full page as mentioned. Either duplicate the camp info on the trail section card or remove the camp info from the card and only have it via this popup/full page so that it's completely separate ?

**Comment by brettmarl** [comment]
started to lay some ground work for this by changing the icon-interaction to a sliding drawer vs a popup dialog. i've tried a few times to make this change, but am struggling getting and icon into the black/white placeholder in a way that doesn't a) eat too much space and b) look for for small and long place-names. 

might be easier to add a camp-icon to the locations and bail on interactive place-names idea...

**Comment by brettmarl** [comment]
this is in latest build, but non-camp placename interactions are currently blank. anything we can stay about each spot?

**Comment by brettmarl** [comment]
done
